version: '3'
services:
    proxy:
        image: nginx:latest   # 최신 버전의 Nginx 사용
        container_name: proxy # container 이름은 proxy
        ports: 
            - "80:80"           # 80번 포트를 host와 container 맵핑
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf # nginx 설정 파일 volume 맵핑
        restart: "unless-stopped" # 내부에서 에러로 인해 container가 죽을 경우 restart
    express:
        build:
            context: ./backend  # 빌드할 Dockerfile이 위치한 경로
        image: leaflog-api
        container_name: leaflog-api
        expose:
            - "3000"           # 다른 컨테이너에게 3000번 포트 open
        volumes:
            - ./backend:/source # host <-> container의 source 디렉토리를 공유
            - /source/node_modules # !!!!!!!! Dockerfile 설명에서 다시 설명합니다.
        restart: "unless-stopped"
    front:
        build:
            context: ./frontend  # 빌드할 Dockerfile이 위치한 경로
        image: leaflog-front
        container_name: leaflog-front
        expose:
            - "8080"
        ports: 
            - "8080:8080" 
        volumes:
            - ./frontend:/dist # host <-> container의 source 디렉토리를 공유
        restart: "unless-stopped"